{{- if .Values.databaseSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.databaseSecret.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USERNAME: "postgres_admin"
  DB_PASSWORD: "DO_NOT_USE_IN_PRODUCTION_PLACEHOLDER"
{{- end }}