apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "my-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http-api
      protocol: TCP
      name: http-api
  selector:
    app.kubernetes.io/component: backend